import { ThemeType } from '../types';

// Define theme-specific styles and configurations
export const themeConfig = {
  modern: {
    primaryColor: '#6366f1', // Indigo
    secondaryColor: '#8b5cf6', // Violet
    backgroundColor: '#f9fafb', // Light gray
    textColor: '#1f2937', // Dark gray
    accentColor: '#ec4899', // Pink
    fontFamily: "'Poppins', sans-serif",
    borderRadius: '0.5rem',
    cardStyle: 'shadow-lg rounded-lg bg-white',
    buttonStyle: 'bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-md transition-all',
    outlineButtonStyle: 'bg-transparent border-2 border-white text-white hover:bg-white/10',
    headerStyle: 'bg-gradient-to-br from-indigo-600 via-purple-500 to-pink-400',
    headerTextStyle: 'text-white',
    headerSubtitleStyle: 'text-white/80',
    profileImageStyle: 'rounded-full border-4 border-indigo-300',
    profileContainerStyle: 'bg-indigo-100/30 backdrop-blur-sm rounded-full p-4',
    profileGradientStyle: 'bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500',
    profileBlurStyle: 'bg-indigo-500',
    profileBadgeStyle: 'bg-indigo-600',
    animation: 'transition-all duration-300 ease-in-out',
    aboutCardStyle: 'bg-white shadow-md hover:shadow-lg',
    aboutImageStyle: 'rounded-2xl overflow-hidden transform rotate-3',
    iconColor: 'text-indigo-600',
    sectionButtonStyle: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    experienceSectionStyle: 'bg-white',
    experienceCardStyle: 'bg-white shadow-lg hover:shadow-xl',
    experienceTitleStyle: 'text-indigo-900 border-b-2 border-indigo-100 pb-4',
    portfolioSectionStyle: 'bg-gray-50',
    portfolioCardStyle: 'bg-white shadow-lg hover:shadow-xl',
    portfolioButtonStyle: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    portfolioOutlineButtonStyle: 'border-2 border-indigo-600 text-indigo-600 hover:bg-indigo-50',
    portfolioTagStyle: 'bg-indigo-100 text-indigo-800',
    contactSectionStyle: 'bg-white',
    contactCardStyle: 'bg-white shadow-lg hover:shadow-xl',
    contactInputStyle: 'border border-gray-300 focus:border-indigo-500 rounded-md',
    contactButtonStyle: 'bg-indigo-600 hover:bg-indigo-700 text-white',
    footerStyle: 'bg-indigo-900 text-white',
    footerLinkStyle: 'text-white hover:text-indigo-300',
    footerIconStyle: 'bg-indigo-800 hover:bg-indigo-700',
    navStyle: 'bg-indigo-100/30 backdrop-blur-md',
    navActiveStyle: 'bg-indigo-600 text-white',
    navInactiveStyle: 'bg-transparent text-indigo-900 hover:bg-indigo-200',
    themeSwitcherButtonStyle: 'bg-indigo-600 text-white',
    themeSwitcherActiveStyle: 'bg-indigo-100 text-indigo-700 font-medium',
  },
  desi: {
    primaryColor: '#e11d48', // Rose/Red
    secondaryColor: '#fbbf24', // Amber
    backgroundColor: '#fffbeb', // Light amber
    textColor: '#44403c', // Brown
    accentColor: '#15803d', // Green
    fontFamily: "'Mukta', sans-serif",
    borderRadius: '0.75rem',
    cardStyle: 'shadow-md rounded-lg bg-white border-2 border-amber-200',
    buttonStyle: 'bg-amber-500 hover:bg-amber-600 text-white font-medium py-2 px-4 rounded-md transition-all',
    outlineButtonStyle: 'bg-transparent border-2 border-rose-600 text-white hover:bg-rose-600/10',
    headerStyle: 'bg-gradient-to-br from-rose-600 via-amber-400 to-amber-200',
    headerTextStyle: 'text-white',
    headerSubtitleStyle: 'text-white/80',
    profileImageStyle: 'rounded-full border-4 border-amber-300',
    profileContainerStyle: 'bg-amber-100/30 backdrop-blur-sm rounded-full p-4 border-2 border-amber-200',
    profileGradientStyle: 'bg-gradient-to-br from-rose-500 to-amber-400',
    profileBlurStyle: 'bg-rose-500',
    profileBadgeStyle: 'bg-amber-400',
    animation: 'transition-all duration-300 ease-in-out',
    aboutCardStyle: 'bg-amber-50 border-2 border-amber-200 hover:border-amber-300',
    aboutImageStyle: 'rounded-lg overflow-hidden border-4 border-amber-300 transform -rotate-3',
    iconColor: 'text-rose-600',
    sectionButtonStyle: 'bg-rose-600 hover:bg-rose-700 text-white',
    experienceSectionStyle: 'bg-amber-50',
    experienceCardStyle: 'bg-white border-2 border-amber-200 hover:border-amber-300',
    experienceTitleStyle: 'text-amber-800 border-b-2 border-amber-200 pb-4',
    portfolioSectionStyle: 'bg-amber-50',
    portfolioCardStyle: 'bg-white border-2 border-amber-200 hover:border-amber-300',
    portfolioButtonStyle: 'bg-rose-600 hover:bg-rose-700 text-white',
    portfolioOutlineButtonStyle: 'border-2 border-rose-600 text-rose-600 hover:bg-rose-50',
    portfolioTagStyle: 'bg-amber-100 text-amber-800',
    contactSectionStyle: 'bg-amber-50',
    contactCardStyle: 'bg-white border-2 border-amber-200 hover:border-amber-300',
    contactInputStyle: 'border-2 border-amber-200 focus:border-rose-500 rounded-lg',
    contactButtonStyle: 'bg-rose-600 hover:bg-rose-700 text-white',
    footerStyle: 'bg-rose-700 text-white',
    footerLinkStyle: 'text-white hover:text-amber-300',
    footerIconStyle: 'bg-rose-800 hover:bg-rose-600',
    navStyle: 'bg-amber-100 border-2 border-amber-300',
    navActiveStyle: 'bg-rose-600 text-white',
    navInactiveStyle: 'bg-transparent text-amber-900 hover:bg-amber-200',
    themeSwitcherButtonStyle: 'bg-rose-500 text-white',
    themeSwitcherActiveStyle: 'bg-rose-100 text-rose-700 font-medium',
  },
  minimal: {
    primaryColor: '#262626', // Neutral-800
    secondaryColor: '#525252', // Neutral-600
    backgroundColor: '#fafafa', // Neutral-50
    textColor: '#171717', // Neutral-900
    accentColor: '#737373', // Neutral-500
    fontFamily: "'Inter', sans-serif",
    borderRadius: '0.25rem',
    cardStyle: 'border border-neutral-200 rounded-sm bg-white',
    buttonStyle: 'bg-neutral-900 hover:bg-black text-white font-medium py-2 px-4 rounded-sm transition-all',
    outlineButtonStyle: 'bg-transparent border-2 border-neutral-800 text-neutral-800 hover:bg-neutral-100',
    headerStyle: 'bg-neutral-100',
    headerTextStyle: 'text-neutral-900',
    headerSubtitleStyle: 'text-neutral-600',
    profileImageStyle: 'rounded-full',
    profileContainerStyle: 'bg-white rounded-full p-4 shadow-sm',
    profileGradientStyle: 'bg-gradient-to-b from-neutral-300 to-neutral-500',
    profileBlurStyle: 'bg-neutral-400',
    profileBadgeStyle: 'bg-neutral-800',
    animation: 'transition-all duration-200 ease-in-out',
    aboutCardStyle: 'bg-white border border-neutral-200 hover:border-neutral-300',
    aboutImageStyle: 'rounded-sm overflow-hidden',
    iconColor: 'text-neutral-800',
    sectionButtonStyle: 'bg-neutral-900 hover:bg-black text-white',
    experienceSectionStyle: 'bg-white',
    experienceCardStyle: 'bg-neutral-50 border border-neutral-200',
    experienceTitleStyle: 'text-neutral-900 border-b border-neutral-200 pb-4',
    portfolioSectionStyle: 'bg-gray-50',
    portfolioCardStyle: 'bg-white border border-neutral-200 hover:border-neutral-300',
    portfolioButtonStyle: 'bg-neutral-900 hover:bg-black text-white',
    portfolioOutlineButtonStyle: 'border border-neutral-800 text-neutral-800 hover:bg-neutral-100',
    portfolioTagStyle: 'bg-neutral-100 text-neutral-700',
    contactSectionStyle: 'bg-white',
    contactCardStyle: 'bg-white border border-neutral-200 hover:border-neutral-300',
    contactInputStyle: 'border border-neutral-300 focus:border-neutral-800 rounded-sm',
    contactButtonStyle: 'bg-neutral-900 hover:bg-black text-white',
    footerStyle: 'bg-neutral-900 text-white',
    footerLinkStyle: 'text-white hover:text-neutral-300',
    footerIconStyle: 'bg-neutral-800 hover:bg-neutral-700',
    navStyle: 'bg-white border border-neutral-200',
    navActiveStyle: 'bg-neutral-900 text-white',
    navInactiveStyle: 'bg-transparent text-neutral-700 hover:bg-neutral-100',
    themeSwitcherButtonStyle: 'bg-neutral-800 text-white',
    themeSwitcherActiveStyle: 'bg-neutral-100 text-neutral-800 font-medium',
  },
};

export const getThemeStyles = (theme: ThemeType) => {
  return themeConfig[theme];
};